Chore/output file name
bytedance/byteinspire-js-sdk pull request #1
Opened 2021-06-10 06:59 UTC by Margaux7

1. 更新 readme，补充发布流程规范
2. mp 和 browser 版本编译后的文件名增加版本号
3. 设置 commit message lint hook
4. package.json 增加关键字

2021-06-10 07:29 UTC, adcentury requested changes

2021-06-10 07:29 UTC, adcentury commented on README.md
> +1. 提交的 PR 合入 master 后，release-please-action 会自动提交 Release PR，该 PR 会自动修改 CHANGELOG 文件，并更新版本，如果不想在 CHANGELOG 文件出现不相关内容，可以在合入 master 是选择 squash。合入时的 commit message 需要符合以下[规范](https://github.com/marketpl
合入 master **时**

2021-06-10 07:29 UTC, adcentury commented on README.md
> +* fix: 开头，代表修复 bug ，会自动更新 patch 版本
bug 与逗号之间不需要额外空格

2021-06-10 07:29 UTC, adcentury commented on README.md
> +* feat: 开头，代表新的 feature ，会自动更新 minor 版本
同上

2021-06-10 07:29 UTC, adcentury commented on README.md
> +* fix: 开头，代表修复 bug ，会自动更新 patch 版本
另外这里 fix: 最好用代码框框起来，代表是一个整体 `fix:`

2021-06-10 07:29 UTC, adcentury commented on webpack/browser.js
> +const { version } = require('@package/../../package.json');
这个路径为啥长这样？

2021-06-10 07:54 UTC, Margaux7 commented on webpack/browser.js
> +const { version } = require('@package/../../package.json');
复制过来的，历史原因，已修改

2021-07-07 08:29 UTC, adcentury commented
LGTM.

2021-07-07 08:30 UTC, adcentury approved these changes

2021-07-08 06:45 UTC, merged